### ISSUE TITLE
希望添加更长时间的预报[FR]

### ISSUE THREAD

**Issue by flypigJ** [zxbmmmmmmmmm/SkylineWeather#32]
- Windows版本:all supported

**此功能请求是否与问题/Bug有关？无
**功能内容**
希望添加更长时间的预报，如：https://www.msn.cn/zh-cn/weather/monthlyforecast/in-%E4%B8%8A%E6%B5%B7%E5%B8%82,%E9%97%B5%E8%A1%8C%E5%8C%BA?loc=eyJsIjoi6Ze16KGM5Yy6IiwiciI6IuS4iua1t%2BW4giIsImMiOiLkuK3ljY7kurrmsJHlhbHlkozlm70iLCJpIjoiQ04iLCJ0IjoxLCJnIjoiemgtY24iLCJ4IjoiMTIxLjQwMTAwMDk3NjU2MjUiLCJ5IjoiMzEuMDY5MDAwMjQ0MTQwNjI1In0%3D&weadegreetype=C&ocid=msedgntp&cvid=c2798d33e55e400f840b0abd5d49c97c   所示
![image](https://github.com/zxbmmmmmmmmm/FluentWeather/assets/68471692/552ad282-019a-4a29-aa47-f18ad300ecc5)
![image](https://github.com/zxbmmmmmmmmm/FluentWeather/assets/68471692/46860235-e56b-4e0a-a569-3516dcdf8153)
当然也可以不要那么久的，也许一个月左右最好？

**实现方法**
也许可以爬取网页内容

**其他信息**
[可选]描述相关信息

**Comment by zxbmmmmmmmmm** [comment]
这个功能以前写过，由于API受限原因隐藏了。
![image](https://github.com/zxbmmmmmmmmm/FluentWeather/assets/96322503/a5c4f7f7-1607-427d-8f89-3617e09e908d)
![image](https://github.com/zxbmmmmmmmmm/FluentWeather/assets/96322503/ec7c365f-49a6-41bb-89d2-9213e7b18ff6)
会考虑加回来（可能要换数据源）

**Comment by zxbmmmmmmmmm** [comment]
下个版本中，将添加“月视图”
需使用Open-Meteo数据源或者和风天气付费KEY。
![image](https://github.com/user-attachments/assets/b17facaf-02d4-4f38-8fe2-854fee933be0)
