### ISSUE TITLE
希望有更多数据能看更直观的图线[FR]

### ISSUE THREAD

**Issue by flypigJ** [zxbmmmmmmmmm/SkylineWeather#33]
- Windows版本:all supported

**此功能请求是否与问题/Bug有关？请描述**
无

**功能内容**
希望有更多数据能看更直观的图线。如：https://www.msn.cn/zh-cn/weather/hourlyforecast/in-%E4%B8%8A%E6%B5%B7%E5%B8%82,%E9%97%B5%E8%A1%8C%E5%8C%BA?loc=eyJsIjoi6Ze16KGM5Yy6IiwiciI6IuS4iua1t%2BW4giIsImMiOiLkuK3ljY7kurrmsJHlhbHlkozlm70iLCJpIjoiQ04iLCJ0IjoxLCJnIjoiemgtY24iLCJ4IjoiMTIxLjQwMTAwMDk3NjU2MjUiLCJ5IjoiMzEuMDY5MDAwMjQ0MTQwNjI1In0%3D&weadegreetype=C&ocid=msedgntp&cvid=df3ac59f788c4bc9a631a80b5f746a5c
![image](https://github.com/zxbmmmmmmmmm/FluentWeather/assets/68471692/3fd1b6d1-9599-4ec3-b4f3-0eaceaea3b0a)

**实现方法**
爬取msn weather

**其他信息**
[可选]描述相关信息

**Comment by zxbmmmmmmmmm** [comment]
将在1.1.0添加以下图表:
- 风
![image](https://github.com/zxbmmmmmmmmm/SkylineWeather/assets/96322503/59c9c208-2dea-4aab-b994-f6944ba2b169)
- 湿度
![image](https://github.com/zxbmmmmmmmmm/SkylineWeather/assets/96322503/4fa2c410-32df-422d-9fb1-da925c8fb84c)
- 气压
![image](https://github.com/zxbmmmmmmmmm/SkylineWeather/assets/96322503/bd722fcb-35cb-427c-997a-970a3ebb16b5)
- 能见度(仅Open-Meteo)
![image](https://github.com/zxbmmmmmmmmm/SkylineWeather/assets/96322503/4cba10ad-2330-460a-b247-5052ea25278d)
- 云量
![image](https://github.com/zxbmmmmmmmmm/SkylineWeather/assets/96322503/1b86d0df-7123-4b46-8b35-b61566dccdaf)
