### ISSUE TITLE
[FR]希望增加Windows10系统下不同地区多磁贴显示支持

### ISSUE THREAD

**Issue by mingqiannailv** [zxbmmmmmmmmm/SkylineWeather#49]
- Windows版本:19044.4412
 - 1.1.0(2024/5/5)

**功能内容**
希望能够增加类似Bing天气类似的多地区天气可拆分磁贴固定的功能
![屏幕截图 2024-05-27 100332](https://github.com/zxbmmmmmmmmm/SkylineWeather/assets/110336013/0da7b963-f656-4c88-82f4-d64ee640b6dd)

**实现方法**
类似Bing天气在应用内不同地区天气页面增加磁贴固定的选项
![屏幕截图 2024-05-27 100439](https://github.com/zxbmmmmmmmmm/SkylineWeather/assets/110336013/67c5c82b-414b-40ac-adc0-34d17e21ad5a)

**Comment by zxbmmmmmmmmm** [comment]
会考虑实现，但动态辅助磁贴可能还得晚些
