### ISSUE TITLE
[BUG] 如果单击 Toast 通知来启动应用，则应用显示不正常

### ISSUE THREAD

**Issue by Baka632** [zxbmmmmmmmmm/SkylineWeather#52]
- Windows版本: Windows 11 22631.3737
 - 应用版本: 1.1.1.0

**问题描述**
单击 Toast 通知来启动应用，应用的主页面显示不正常

**重现步骤**
1. 点击通知来启动应用
2. 应用启动后，应用界面不能正常加载

**期望的行为**
应用界面应当正常显示。

**屏幕截图**
![屏幕截图 2024-06-21 135416](https://github.com/zxbmmmmmmmmm/SkylineWeather/assets/48171809/83914734-48df-439a-9afb-43fa8609eed8)

**其他信息**
问题可能出在 `App.xaml.cs` 的 `OnActivated` 方法中，也许这里缺少了某些关键的配置？

**Comment by zxbmmmmmmmmm** [comment]
刚刚测试了一下，似乎没有问题...

**Comment by zxbmmmmmmmmm** [comment]
实际使用时仍然会发生此问题。。需要定位bug

**Comment by Baka632** [comment]
此问题已在 1.3.0.0 版本中解决

**Comment by zxbmmmmmmmmm** [comment]
> 此问题已在 1.3.0.0 版本中解决

奇怪了，我没有特意修这个bug。。但是偶尔就会出来
等定位到问题所在再打开罢

**Comment by zxbmmmmmmmmm** [comment]
已彻底修复.
