### ISSUE TITLE
[FR] 优化天气信息显示

### ISSUE THREAD

**Issue by MyBlueHorizon** [zxbmmmmmmmmm/SkylineWeather#57]
- Windows版本: Windows 10 22H2（19045.4651）
 - 应用版本:1.3.0.0

**功能内容**
添加选项允许将风向、湿度等信息提升至上部显示，同时将露点温度单独显示。

**其他信息**
在1080p屏幕分辨率、125%放大下，若最大化应用，这些信息需要向下滚动才能看到。
这些信息较为重要，需要更加直观的展示。

**Comment by zxbmmmmmmmmm** [comment]
此功能可使用**个性化->自定义主页**实现
![image](https://github.com/user-attachments/assets/4f2960f6-a410-4041-95d8-4b1923647a20)
下载：https://github.com/zxbmmmmmmmmm/SkylineWeather/discussions/38
