### ISSUE TITLE
[FR] 自訂區塊順序

### ISSUE THREAD

**Issue by AkazaRenn** [zxbmmmmmmmmm/SkylineWeather#61]
- Windows版本: Windows 11 24H2 26100.1301
 - 应用版本: 1.3.1.0

**功能内容**
自訂區塊順序，我個人更偏好把今日天氣放在前面，然後再是本週天氣，希望可以支持這樣的選項。

**Comment by zxbmmmmmmmmm** [comment]
可使用**设置->自定义主页**实现
![image](https://github.com/user-attachments/assets/8705baad-2bb8-4904-876c-667d30170c9c)
下载:https://github.com/zxbmmmmmmmmm/SkylineWeather/discussions/62
