### ISSUE TITLE
[BUG]通知文本格式錯誤 - 英文

### ISSUE THREAD

**Issue by AkazaRenn** [zxbmmmmmmmmm/SkylineWeather#65]
- Windows版本: Windows 11 Pro 24H2 26100.1301
 - 应用版本: 1.3.1.0

**问题描述**
天氣後有多餘空格且缺乏標點符號，溫度數字前缺空格。最好可以加上是攝氏度還是華式度，因為有這個選項。

**重现步骤**
简单描述重现此问题的步骤，例如:
1. 開啟天氣通知
2. 等待天氣通知到達
3. 發現錯誤

**期望的行为**
我個人認為正確的格式是以下幾種：
- `Fog, highest 25 °C, lowest 14 °C`
- `Fog - Highest 25 °C - Lowest 14 °C`
- `Fog ⬆️25 °C ⬇️14 °C`

**屏幕截图**
<img width="150" alt="Screenshot 2024-08-13 103108" src="https://github.com/user-attachments/assets/c37c276b-8cff-4b96-85ae-6359fc6decd3">

**其他信息**
[可选]添加问题的相关信息

**Comment by zxbmmmmmmmmm** [comment]
![image](https://github.com/user-attachments/assets/473fc10b-03af-4dae-81f6-7d2a656be4b1)
fixed
