### ISSUE TITLE
[FR]顶栏显示效果优化

### ISSUE THREAD

**Issue by Mark3521** [zxbmmmmmmmmm/SkylineWeather#67]
将页面向上滚动一些后，顶栏的显示内容会和页面内容起冲突，建议给顶栏加一个亚克力模糊效果优化一下
![{B2A0BEB2-5B1D-49FD-B660-F602A5AB8932}](https://github.com/user-attachments/assets/7539434d-6da1-4d71-9fa2-bc6ecb4ad64a)

**Comment by zxbmmmmmmmmm** [comment]
![image](https://github.com/user-attachments/assets/6096b9b3-a542-4035-987b-e8f3980d5eb3)
fixed
